spring.application.name=devvault

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/devvault
spring.datasource.username=postgres
spring.datasource.password=kush

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false
encryption.key=12345678901234567890123456789012

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=300000